[package]
name = "test-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
base64ct.workspace = true
cargo_metadata.workspace = true
josekit.workspace = true
predicates.workspace = true
thiserror.workspace = true
