[source."git+https://github.com/domisafonov/josekit-rs.git"]
git = "https://github.com/domisafonov/josekit-rs.git"
replace-with = "vendored-sources"

[source."git+https://github.com/domisafonov/rexpect.git?branch=openbsd"]
git = "https://github.com/domisafonov/rexpect.git"
branch = "openbsd"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendored"
