[package]
name = "dumbnotesd"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
boolean-enums.workspace = true
clap.workspace = true
dumbnotes.path = "../dumbnotes"
figment.workspace = true
futures.workspace = true
josekit.workspace = true
log.workspace = true
prost.workspace = true
rocket.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
unix.path = "../unix"
uuid.workspace = true

[dev-dependencies]
assert_fs.workspace = true
rexpect.workspace = true
test-utils.path = "../test-utils"

[build-dependencies]
prost-build.workspace = true

[lints]
workspace = true
