[package]
name = "dumbnotesd"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
boolean-enums.workspace = true
clap.workspace = true
figment.workspace = true
futures.workspace = true
log.workspace = true
prost.workspace = true
rocket.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
uuid.workspace = true
josekit.workspace = true
dumbnotes.path = "../dumbnotes"

[build-dependencies]
prost-build.workspace = true
